### ISSUE TITLE
Token not found for private repository

### ISSUE THREAD

**Issue by tndev** [sindresorhus/package-json#18]
I have a `.npmrc` file that looks like this:

    always-auth=true
    registry=https://npm.tn-dev.com/

If I try get the get the package info e.g. of `mysql` it fails to find the corresponding token. The problem seems to be that it is looking for `mysql:_authToken`  instead of `//npm.tn-dev.com/:_authToken` in the `npmrc`

the following change to the code solves the problem for me, but I'm not sure if this is really bug/problem of the library or if it is a problem with my setup:
    
    var token = npmrc[scope + ':_authToken'] || npmrc['//registry.npmjs.org/:_authToken'] || npmrc[registryUrl(scope).replace(/^https:/,'')+':_authToken'];

**Comment by sindresorhus** [comment]
I don't know. I have only used the public endpoint.

It was added in https://github.com/sindresorhus/package-json/pull/13. Maybe @dylang @homerjam could help.

**Comment by dylang** [comment]
Hi @tndev, it's currently working for me. 

```
> var packageJson = require('package-json')
> packageJson('mysql', 'latest').then(console.log)
Promise { <pending> }
> { name: 'mysql',
  description: 'A node.js driver for mysql. It is written in JavaScript, does not require compiling, and is 100% MIT licensed.',
  version: '2.10.0',
  license: 'MIT',
  author:
   { name: 'Felix Geisendörfer',
     email: 'felix@debuggable.com',
     url: 'http://debuggable.com/' },
  contributors:
....
```

However, my `npmrc` settings are little different:

```
registry=http://npm.<my company's domain>/
always-auth=false
strict-ssl=false
```

**Comment by tndev** [comment]
Hi @dylang, I think I found out what the problem might be. 

In my setup all packages (private and public) are installed through my private repos and no matter if I access the public or private packages a password is required. It looks like this is the reason for the problem.

I would guess that in your setup `mysql` is either downloaded from `npmjs.com` directly or does not require a password/token. Can you confirm this?

If this is the case, then I think that my change to the code could be a valid fix for this situation.

**Comment by dylang** [comment]
@tndev that is correct, any tarballs for public packages are downloading from the public cdn.
