### ISSUE TITLE
scoped package support

### ISSUE THREAD

**Issue by hbetts** [sindresorhus/package-json#2]
I'm interested in using [update-notifier](https://github.com/yeoman/update-notifier) for scoped packages.

However, looking into `package-json` and `registry-url`, I don't believe it's possible to use `update-notifier`  with a package that has been installed via `npm install @myco/mypackage` after having set the appropriate [npm scope](https://docs.npmjs.com/misc/scope) config option `npm config set @myco:registry http://reg.example.com`.

It looks like [registry-url](https://github.com/sindresorhus/registry-url/blob/master/index.js) will only retrieve a catch-all registry override, `registry`, and not scope registries.

Perhaps it's possible to either pass in the name of a scope to `registry-url`, or just have `registry-url` return all registries in the `.npmrc` file such that `package-json` can choose the appropriate one?

**Comment by sindresorhus** [comment]
> package-json can choose the appropriate one?

How would it choose the appropriate one?

**Comment by hbetts** [comment]
@sindresorhus, on further thought, I don't believe my suggestion _package-json can choose the appropriate one_ is an appropriate approach to this problem. First, I believe it's out of scope for `registry-url` to return a list of registry urls. It is, after all, singular, not plural. Second, `registry-url` would need to check every property name returned by `require('rc')('npm')` for the `registry` sub-string.

Instead, I would like to visit my former suggestion in more depth. Perhaps refactor `registry-url` into the following:

```javascript
'use strict';
module.exports = function(scope) {
  var rc = require('rc')('npm');
  return rc[scope + ':registry'] || rc.registry || 'https://registry.npmjs.org/';
};
```

Then the following naive approach in `package-json`:

```
diff --git i/index.js w/index.js
index 3a8a4a0..d96bddc 100644
--- i/index.js
+++ w/index.js
@@ -3,12 +3,14 @@ var got = require('got');
 var registryUrl = require('registry-url');
 
 module.exports = function (name, version, cb) {
+       var url = registryUrl(name.split('/')[0]);
+
        if (typeof version !== 'string') {
                cb = version;
                version = '';
        }
 
-       got(registryUrl + encodeURIComponent(name) + '/' + version, function (err, data) {
+       got(url + encodeURIComponent(name) + '/' + version, function (err, data) {
                if (err && err.code === 404) {
                        cb(new Error('Package or version doesn\'t exist'));
                        return;
```

**Comment by sindresorhus** [comment]
When a `scope` is defined and the registry can't be found, should it really fall back to the normal registry? Is this what `npm` does? I have no idea how scoped packages works tbh.

**Comment by hbetts** [comment]
@sindresorhus, my impression, based on [npm-scope](https://docs.npmjs.com/misc/scope), and the [npm blog](http://blog.npmjs.org/post/98131109725/npm-2-0-0), is that the public registry will have support for private modules using package scopes.

Therefore, the expected behavior would be to look up a package, regardless of scope, in the public registry unless there is a scope mapping in the user's `.npmrc` file.

A simple test:

```bash
(~)-()--> npm install @myco/package --verbose
npm info it worked if it ends with ok
npm verb cli [ 'node',
npm verb cli   '/home/hutson/.local/bin/npm',
npm verb cli   'install',
npm verb cli   '@myco/package',
npm verb cli   '--verbose' ]
npm info using npm@2.3.0
npm info using node@v0.10.33
npm verb config Skipping project config: /home/hutson/.npmrc. (matches userconfig)
npm verb cache add spec @myco/package
npm verb addNamed @myco/package@*
npm verb mapToRegistry no registry URL found in name for scope @myco
npm verb addNameRange registry:https://registry.npmjs.org/@myco%2fpackage not in flight; fetching
npm verb request uri https://registry.npmjs.org/@myco%2fpackage
npm verb request no auth needed
npm info attempt registry request try #1 at 21:54:26
npm verb request id cc6018367d12a4ef
npm http request GET https://registry.npmjs.org/@myco%2fpackage
npm http 404 https://registry.npmjs.org/@myco%2fpackage
```

Lastly, based on [line 41](https://github.com/npm/npm/blob/fb8e31b95476a50bda35a665a99eec8a5d25a4db/lib/utils/map-to-registry.js#L41) of `map-to-registry`, the default is to always fallback to the default npm registry.

**Comment by sindresorhus** [comment]
Alright. Thanks for clarifying and looking into this. Your above diff looks good. PRs welcome then :)
