### ISSUE TITLE
Support HTTP_PROXY / HTTPS_PROXY use with "got" package

### ISSUE THREAD

**Issue by pilsy** [sindresorhus/package-json#22]
This is so that update-notifier will correctly handle proxies

See https://www.npmjs.com/package/got#proxies for information about using proxies with got

**Comment by sindresorhus** [comment]
Not interested in adding extra stuff for proxy support here. Builtin proxy support is planned for `got` and you could help out with that instead.

**Comment by pilsy** [comment]
`got` already supports proxies, and while you "could" make it look at process.env.HTTP_PROXY and process.env.HTTPS_PROXY and then setup an agent for it, but i figured that it wasn't the place for it... for instance i may want to use the `got` package with multiple proxies in a programmatic fashion so why would it lock you into using those variables.

It would be as simple as, passing an agent parameter with your call to `got` on line 23 of index -- much like https://github.com/CleverStack/cleverstack-cli/commit/5b15523123280fbec97211581fa4d7051f706b39#diff-ad4f0d8fb92260728a1b559aed92cd81R89

**Comment by sindresorhus** [comment]
I'm not going to add custom proxy logic to every single package I have that uses `got`.

:arrow_right: https://github.com/sindresorhus/got/issues/79 :arrow_left:
