### ISSUE TITLE
if registry doens't end in /, scoped packages return `Basic authentication must be done with auth option`

### ISSUE THREAD

**Issue by dylang** [sindresorhus/package-json#25]
### Set up

```bash
# custom registry for specific scope
# notice example.com doesn't end in a slash!
$ npm config set @dylang:registry http://example.com
```

```js
// scoped package that matches custom registry
packageJson('@dylan/scoped-test').then(...)
```

**Error**
```
Registry error Basic authentication must be done with auth option
```

### What's happening

[index.js #L9-10](https://github.com/sindresorhus/package-json/blob/7183d298faa59a8f36edb59f7c5edc693874bb9a/index.js#L9-L10):

```js
var url = registryUrl(scope) +
		encodeURIComponent(name).replace(/^%40/, '@');
```

This results in the url:

```
http://example.com@dylang/%2Fscoped-test
```

### Solutions

* Use node's [url](https://nodejs.org/dist/latest-v4.x/docs/api/url.html) to generate the url, just to be safe.
* Change [registry-url](https://github.com/sindresorhus/registry-url) to append a `/` if it's not there.
* Tell everyone to end their custom registry setting with a `/`. :smile:

**Comment by SamVerschueren** [comment]
[url.resolve](https://nodejs.org/dist/latest-v4.x/docs/api/url.html#url_url_resolve_from_to) should be used here.

**Comment by sindresorhus** [comment]
Good issue! Thanks for taking the effort :)

-

> Change registry-url to append a / if it's not there.

It already does this, but seems the scoped registry case was missed: https://github.com/sindresorhus/registry-url/blob/65d74b13db17ba604fdae24ff2f39879b57f0a4b/index.js#L4

-

PR welcome. Otherwise I'll get to it next week when I have some more time.

**Comment by SamVerschueren** [comment]
@sindresorhus Should it be fixed in `registry-url` or in `package-json` with `url.resolve`? Using `url.resolve` should be added anyways in my opinion. Paths shouldn't be joined with normal string concatenation as well.

**Comment by sindresorhus** [comment]
Both. `registry-url` can be used independently, but still nice to do it properly here too.

**Comment by SamVerschueren** [comment]
PRs submitted!
