### ISSUE TITLE
Allow to work with custom NPM registry

### ISSUE THREAD

**Issue by ziflex** [sindresorhus/package-json#29]
Hi there,

Are there any plans to add possibility to work with custom NPM registry? (Sinopia)
Can create PR if needed.

**Comment by sindresorhus** [comment]
It works with any npm compatible custom registry and adheres to whatever's in `.npmrc`. Not interested in adding custom logic for non-compatible registries though.

**Comment by ziflex** [comment]
@sindresorhus my idea was to allow set registry url programmatically like it's done in official npm registry client
https://github.com/npm/npm-registry-client
