### ISSUE TITLE
feature request: make it isomorphic

### ISSUE THREAD

**Issue by Offirmo** [sindresorhus/package-json#37]
by using isomorphic-fetch or whatever equivalent (or making "got" isomorphic), we could make this module isomorphic, which would be nice for web apps wanting to check their version!

**Comment by Offirmo** [comment]
Btw this module and the chain of underlying modules are awesome. Thanks!

**Comment by sindresorhus** [comment]
Nah, I don't want to deal with the browser. Maybe someday `fetch()` will be good enough for Got to be based on it, but it's not today.

**Comment by rexxars** [comment]
It's also not possible currently, as the npm registry (and I would assume most private registries) do not send any CORS-headers.

**Comment by Offirmo** [comment]
@rexxars @sindresorhus thanks for those precious insights
