### ISSUE TITLE
Feature: Explicit registry parameter

### ISSUE THREAD

**Issue by LayZeeDK** [sindresorhus/package-json#39]
I am using [Verdaccio](https://github.com/verdaccio/verdaccio) with Active Directory authentication. I wanted to use [`auto-dist-tag`](https://github.com/Turbo87/auto-dist-tag) which uses `package-json`.

In your README, you specify that
>Both public and private registries are supported, for both scoped and unscoped packages, as long as the registry uses either bearer tokens or basic authentication.

It does not seem that Verdaccio with Active Directory uses either.

Because of this, I ask that we add a parameter to use a specific registry. Other solutions are welcome.

More details of my setup in https://github.com/Turbo87/auto-dist-tag/issues/8

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in adding an option for this. It would add a burden on modules depending on this module as they too would need to support such option. I don't really know what's wrong. You're on your own when you use unofficial registry proxies like Verdaccio. Maybe try opening an issue on Verdaccio and ask about authentication.

**Comment by sindresorhus** [comment]
Slightly related: `dist-tags` doesn't even work on Verdaccio: https://github.com/verdaccio/verdaccio/issues/134

**Comment by LayZeeDK** [comment]
That is why I am looking into `auto-dist-tag`.
