### ISSUE TITLE
Git url support

### ISSUE THREAD

**Issue by IonicaBizau** [sindresorhus/package-json#4]
Would be nice to support git urls as well.

```js
require("package.json")("git@github.com:sindresorhus/package-json.git", console.log);
```

What do you think?

**Comment by sindresorhus** [comment]
Why? What's your use-case?

**Comment by IonicaBizau** [comment]
Would be useful for npm packages which are not published on the npm, but are available only in git repos.

NPM supports installing dependencies from git urls.

**Comment by IonicaBizau** [comment]
Just open-sourced [`package.json`](https://github.com/IonicaBizau/package.json): it reads the package.json from npm (using `package-json`) or from git, using [`git-package-json`](https://github.com/IonicaBizau/git-package-json). Hope it helps someone. :grin:
