### ISSUE TITLE
Add gotOpts

### ISSUE THREAD

**Issue by duncanfwalker** [sindresorhus/package-json#41]
I see that since the proxy request was closed ( https://github.com/sindresorhus/package-json/issues/22) proxy support has been added to got.

I would like to be able to pass options through to got so that I can use a tunneling agent over a proxy.

Would you consider a pull request to add this in? If you are I'd be happy to have a go.

**Comment by duncanfwalker** [comment]
Hi @sindresorhus - do you think you would be open to a PR for adding those options in? I know it isn't priority for a lot of people but I imagine there are a few people trying to use this in corporate environments

**Comment by sindresorhus** [comment]
Probably not, sorry. My stance is that this should be solved in Node.js, or at the very least in [Got](https://github.com/sindresorhus/got/issues/79) (without any options needed). I'm not interested in having options for this in every module that does any kind of HTTP. If I allow this, I'm gonna get requests for this kind of option in every module that depends on `package-json`, etc etc.
