### ISSUE TITLE
Add parsing of package@version

### ISSUE THREAD

**Issue by realies** [sindresorhus/package-json#42]
Most commands in the yarn/npm CLIs support passing version after `@`, would be great if `package-json` has this too.

**Comment by sindresorhus** [comment]
It could be supported in https://github.com/sindresorhus/package-json-cli, but it's out of scope of this module.

**Comment by astorije** [comment]
@sindresorhus, the rationale behind this is that [here](https://github.com/thelounge/thelounge/pull/2161/files#diff-862474bcfc209ab6eb96e6c572892832R26), we have to extract the version ourselves when passing it to `package-json`. We can't use `package-json-cli` by definition.
I still think it would be valuable in this module, so any consumer could rely on your module to correctly do the parsing upstream.
