### ISSUE TITLE
Support usage behind proxy

### ISSUE THREAD

**Issue by casieber** [sindresorhus/package-json#54]
#43 was closed as a dupe of #22. And in #22 you said:

> Not interested in adding extra stuff for proxy support here. Builtin proxy support is planned for got and you could help out with that instead.

However on Sept 4th, 2018 you then closed sindresorhus/got#79 saying:

>It's just too complicated and would bloat Got.

You passed the issue upstream initially but now have passed it back downstream to yourself here. So, any chance of supporting HTTP_PROXY / HTTPS_PROXY?

**Comment by sindresorhus** [comment]
You can use https://github.com/gajus/global-agent for proxy support.
