### ISSUE TITLE
Calling got with no retry limit causes infinite retries when request timeout.

### ISSUE THREAD

**Issue by Xdminsy** [sindresorhus/package-json#60]
My connection to the npm registry is so bad, it always timeout.
So today I install yeoman from the Taobao registry and it hangs on post-install script `yo doctor` after printing out `npm version`.
After some time debugging I find `yo doctor` when checking `yo-version`, it uses `latest-version` which uses `package-json` to fetch package.json from the network. https://github.com/yeoman/doctor/blob/master/lib/rules/yo-version.js#L17

Then I find that, in https://github.com/sindresorhus/package-json/blob/master/index.js#L71, the `gotOptions` contains no timeout and retry, after trying some breakpoints I find out why it gets stuck.

`got` defaults to no retry limit, and have a random increasing delay between retries, while feeding it no retry option, it always gets an ETIMEOUT on HTTP request and retries, retries, and retries. So my `yo doctor` hangs, and no further output, thus yeoman cannot be installed until I choose `--ignore-scripts`. I tried adding a timeout but it still always retries, so in my view a retry limit is necessary.
Though the version of `package-json` is 4.0.1 in dependencies of `yo doctor`, there's still no retry limit in the current version v6.50 I figure.
I tried adding `retry: 3` and after retries, it returns an ETIMEOUT error, and `package-json` can catch it and rethrow, and `yo doctor` succeed to run the remaining code.

I suggest that `package-json` provide a default retry limit of 5 or 3 or what makes sense, and also provides retry and timeout as options. When a user cannot connect to the registry, it can at least provide some error messages, instead of always retrying so hanging.

**Comment by sindresorhus** [comment]
> got defaults to no retry limit

The Got version used here has a retry limit of 2: https://github.com/sindresorhus/got/tree/a45e071e8dc5027ab9c7fad5919195501cd9e9ca#retry

**Comment by Xdminsy** [comment]
Ohhhhhh sorry, my carelessness, I forget to consider the `got` version.
Thank you remind me of this, maybe I should request `latest-version` to update this dependency.
