### ISSUE TITLE
`AbbreviatedMetadata` type is incorrect

### ISSUE THREAD

**Issue by dlqqq** [sindresorhus/package-json#62]
## To reproduce

```
const metadata: AbbreviatedMetadata = await packageJson('react')
metadata.versions // actually undefined, but has type Readonly<Record<string, AbbreviatedVersion>>
metadata.version // actually a string, but has type unknown
```

It seems strange that the types are broken out-of-the-box. Am I doing something wrong here?

**Comment by diracs-delta** [comment]
I'm on the latest version, `v7.0.0`.

**Comment by tutlam2019** [comment]
For how long does the funds interrupted the dev and update for the latest version?

**Comment by h4xnoodle** [comment]
do this as a workaround
`const { version } = await packageJson(name)`

source: [his other package ](https://github.com/sindresorhus/latest-version/blob/main/index.js#L4)

**Comment by h4xnoodle** [comment]
He ends up doing `const { version } = await packageJson(name)` [in another package that uses this one](https://github.com/sindresorhus/latest-version/blob/main/index.js)

**Comment by sindresorhus** [comment]
`.versions` should be typed to only be able when `{allVersions: true}`.
