### ISSUE TITLE
[React] litteraly crash the app : "TypeError: process.versions.node is undefined"

### ISSUE THREAD

**Issue by c0ncentus** [sindresorhus/package-json#63]
hi,
# step to reproduce 
React ~16 or React 17 (don't matter) 
When this code is in my app all is broken (my app crashed when the first render) I test many times and that's sure this code will provoke the error .... I havn't use it but when require the package .... : 
```javascript
const packageJson = require('package-json');
```
no need more code unfortunaly : / 
I had node 16.3.
I don't know why my node version is important for http request but anyway now current nodejs is v14 so ...

![image](https://user-images.githubusercontent.com/25374826/131220942-7e3b4db3-a74e-4ab7-883e-da546c425771.png)

if don't matter it will be nice to add "no react support" or "no browser support" ? .

I haven't test yet whithout react [...]

**Comment by sindresorhus** [comment]
This package is not really meant to be used in the browser. While it might work, it's up to you to resolve any issues you encounter, like this one.
