### ISSUE TITLE
got dependency need to be update to 11.8.5

### ISSUE THREAD

**Issue by deejaybill** [sindresorhus/package-json#69]
A fix for version 6.5.0 should be done due to the moderate severity vulnerability alert shown via the npm audit command caused by got dependency. The adoption of the ESM-only package is quite slow.

## Steps

npm i package-json@6.5.0
npm audit 

### npm audit report

got  <11.8.5
Severity: moderate
Got allows a redirect to a UNIX socket - https://github.com/advisories/GHSA-pfrx-2q88-qq97
fix available via `npm audit fix --force`
Will install package-json@8.1.0, which is a breaking change
node_modules/got
  package-json  <=6.5.0
  Depends on vulnerable versions of got
  node_modules/package-json

**Comment by sindresorhus** [comment]
Got v11 requires Node.js 10, while `package-json@6.5.0` targets Node.js 8, so that will not work.

There are ways to import the latest package-json from CommonJS: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
