### ISSUE TITLE
Package Metadata URL May be Deprecated

### ISSUE THREAD

**Issue by destroyerofbuilds** [sindresorhus/package-json#7]
Based on this issue (https://github.com/npm/npm/issues/9164), which was a follow up to pull request #6 , it looks like the `<PACKAGE NAME>/<VERSION>` API end-point is going to be deprecated in the future.

**Comment by sindresorhus** [comment]
@destroyerofbuilds Would you be willing to open an issue on their issue tracker, per recommendation:

> If you want an interface like this back / to work with scoped packages, you might want to file an issue describing your use case at https://github.com/npm/public-api/issues/new.

**Comment by destroyerofbuilds** [comment]
@sindresorhus I can do that, but it may be a little longer before I have the time.

Though, I did start to go down the rabbit hole when I was wondering if we could just use the `by-field` end-point to get the `version` field. (Assuming it returned the version field for the latest published version of the package).

However, in attempting to use the same URL generated as part of this project's tests (`https://registry.npmjs.org/-/by-field/?key=%22pageres%22&field=description`) I can't get the value of the `description` field. With a clean checkout of this project the `by-field` test fails.

Now I'm wondering if they removed the `by-field` API end-point.

**Comment by sindresorhus** [comment]
Yeah, I can confirm it no longer works. It did use to work though. Ugh...

Funnily enough, this works: https://skimdb.npmjs.com/registry/_design/app/_view/byField/?key=%22pageres%22&field=description

@othiym23 Was the `by-field` endpoint removed or changed? It's very useful as the full package is giant and just fetching a field, which is the most common use-case, is faster.

**Comment by destroyerofbuilds** [comment]
@sindresorhus npm/public-api#6

**Comment by hbetts** [comment]
I created #9 to focus on the `by-field` end-point.

Leaving this to the scoped packages end-point.

**Comment by hbetts** [comment]
I've filed npm/public-api#11 to get the discussion moving on the version end-point for scoped packages.

**Comment by SamVerschueren** [comment]
@sindresorhus In order to solve this, we can maybe just retrieve the latest release (https://registry.npmjs.org/pageres/latest). It's not the entire package so the size is a lot smaller, but allows us to retrieve the field and keep this method.

**Comment by sindresorhus** [comment]
@SamVerschueren That doesn't work for scoped packages: https://registry.npmjs.org/@sindresorhus%2Fdf/latest

**Comment by SamVerschueren** [comment]
![make-an-api](https://cloud.githubusercontent.com/assets/1913805/10403091/a103ac6c-6ec9-11e5-83e8-82aefb1fec19.jpg)

**Comment by sindresorhus** [comment]
The API is absolutely horrible, but I guess we can look forward a public API in 2020 :p

**Comment by SamVerschueren** [comment]
2020... Someone is having high hopes ;)
