### ISSUE TITLE
Add option to ignore deprecated versions

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [sindresorhus/package-json#70]
When getting the latest minor version of a package (e.g. `^4.5.0`) could we add an option to ignore package versions that are marked as "deprecated" on npmjs.org?

Related: https://github.com/ng-packagr/ng-packagr/issues/2434

**Comment by Blackbaud-SteveBrush** [comment]
For example, `ng-packagr`'s most recent version `14.3.0` is marked as deprecated, but `package-json` pulls it in anyway when I request the "latest" version for the range `^14`.
<img width="763" alt="Screen Shot 2022-09-14 at 10 27 43 AM" src="https://user-images.githubusercontent.com/12497062/190183021-5e1591bb-d480-4441-9111-9a2b678223f3.png">

**Comment by rexxars** [comment]
Seems sensible to me - do you want to take a stab at implementing it?
